### ISSUE TITLE
Cannot Specify Defaults to remove the Robot and Bell Icon

### ISSUE THREAD

**Issue by leew** [andrewchilds/slack-notify#15]
I want to use the defaults that I have configured on Slack, however as each method wraps a call to send, even those using extend({}), there is no way to let the Slack defaults be used. 

I understand that you want to make it easy to work out of the box, but possibly the user defined defaults could be passed in as a second argument when constructing the object. 

This would allow a blank object to be passed in to remove the
`
{ 
     name: "Robot",
     icon_emoji: ":bell:"
}
`

**Comment by briandbermanpf** [comment]
Is there a way to even override Robot (and the bell)?  I'm having the same problem but would be happy if there was "any" way to override.
