### ISSUE TITLE
@channel does not work

### ISSUE THREAD

**Issue by ZiyanK** [andrewchilds/slack-notify#25]
I tried to add an @channel to notify everyone in the channel but it displays as normal text.

**Comment by 00frank** [comment]
Hi @ZiyanK, any workaround you made? I found with the same problem :cry:

**Comment by 00frank** [comment]
Nevermind, forget my comment, you can simply send a message with this syntax: `<!channel>`
Check out the [docs](https://api.slack.com/reference/surfaces/formatting#mentioning-groups)
