### ISSUE TITLE
Revert ESM-only requirement

### ISSUE THREAD

**Issue by jpike88** [andrewchilds/slack-notify#27]
I was using this with esbuild --bundle, and now as ESM only I can't import it, so I just copied the code into my codebase. Please make this cross-compatible with CJS import syntax

**Comment by jpike88** [comment]
legend, thanks

**Comment by andrewchilds** [comment]
@jpike88 thanks for your request. I've published v2.0.1 and verified that both `import` and `require` now work. Can you verify that `esbuild --bundle` works on your end with this version?

**Comment by jpike88** [comment]
weird, it seems to build correctly using esbuild, however vscode does not seem to like the import statement in a typescript file.

![Screen Shot 2022-02-02 at 22 34 04](https://user-images.githubusercontent.com/9585787/152185324-d78cf382-dcf8-4cd8-a531-fc179d4db0a3.png)

**Comment by andrewchilds** [comment]
I think that was the problem, thanks @ThieryMichel. @jpike88, please try again with `2.0.2`.

**Comment by jpike88** [comment]
works good, thanks again
