### ISSUE TITLE
Mismatch in documentation/usage and type definition

### ISSUE THREAD

**Issue by subodhpareek18** [andrewchilds/slack-notify#33]
An example in the documentation to send custom fields is of an object like so:

```js
slack.alert({
  text: 'Current server stats',
  fields: {
    'CPU usage': '7.51%',
    'Memory usage': '254mb'
  }
});
```

But the type definition in index.d.ts is 

```ts
interface SendArgs {
    // ....
    fields?: { [key: string]: string }[];
}
```

Shouldn't it drop the `[]` at the end? Else it becomes array of objects like so `[{key: 'value}, {key: 'value'}]`
```ts
interface SendArgs {
    // ....
    fields?: { [key: string]: string };
}
```

**Comment by andrewchilds** [comment]
This was fixed in `slack-notify@2.0.4`. Thanks!
