### ISSUE TITLE
Default channel name

### ISSUE THREAD

**Issue by podviaznikov** [andrewchilds/slack-notify#5]
Seems like if channel name wasn't specified `#general` would be used: https://github.com/andrewchilds/slack-notify/blob/master/slack-notify.js#L68.

But in slack web interface it's possible to configure default channel name for the incoming webhook.

Can this library not set `#general` as default and rely on the slack web interface?

**Comment by andrewchilds** [comment]
Makes sense, if channel isn't specified in code it should fall back to the UI preference. Will do.

**Comment by podviaznikov** [comment]
see #6

**Comment by andrewchilds** [comment]
`slack-notify@0.1.3` has been published to npm. Thanks!
