### ISSUE TITLE
can't use in meteor

### ISSUE THREAD

**Issue by filipeportes** [andrewchilds/slack-notify#7]
following the steps defined in: https://atmospherejs.com/georgediab/slack-notify

always show this message: No Slack URL configured.

**Comment by roblingle** [comment]
I was able to get this working by adding it to my development_settings.json, and using `meteor --settings config/development_settings.json`. **But** I had to try various URL schemes to get things close to working. I ended up with this, but it's single-channel so all messages go to the same place:

`"slack": "https://hooks.slack.com/services/T0365009U/B090X7SPJ/FINAL_CODE_HERE"`

You get that URL by configuring an [incoming-webhook integration](https://oakworks.slack.com/services). When I tried to go to [this page](https://api.slack.com/web) and create an API token I always got `Error: No hooks` (once I'd defined slack.onError to spit those out). I also tried to re-use my Hubot API key with similar results.

Maybe the URL scheme has changed? I'd like to be able to post to different channels, but I can get by with this.

![slack](https://cloud.githubusercontent.com/assets/12083/9233313/62aa6f1a-4100-11e5-89d8-029e6c2bd027.png)

**Comment by roblingle** [comment]
I noticed that slack.send('some message') seems to escape the configured channel and goes to #general...

**Comment by molinto** [comment]
Same issue here

**Comment by andrewchilds** [comment]
Please take these issues up with the Meteor repo owner. The #general channel issue was fixed in 0.1.4, but according to https://github.com/gdiab/slack-notify/blob/master/package.js that repo is using 0.1.2.
