### ISSUE TITLE
npm registry out of date

### ISSUE THREAD

**Issue by adityabansod** [andrewchilds/slack-notify#9]
in b6e4760aaad2f74c25c7c130795c91fd93775dda i see you updated the `package.json`'s node modules and bumped the version to `0.1.5` (thanks!).

the npm registry still only has up to version `0.1.4`. could you update the registry with `0.1.5`?

```
➜   npm view slack-notify
 
{ name: 'slack-notify',
  description: 'A simple Node.js wrapper around the Slack webhook API.',
  'dist-tags': { latest: '0.1.4' },
  versions: [ '0.1.0', '0.1.1', '0.1.2', '0.1.3', '0.1.4' ]
```

**Comment by andrewchilds** [comment]
Done. Thanks for the reminder @adityabansod!
